# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='purpose_of_trees',
            field=models.CharField(blank=True, choices=[('Tender', 'Tender'), ('Neera', 'Neera'), ('Nut', 'Nut')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], max_length=25),
        ),
    ]
