# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_profile_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='online',
        ),
    ]
