# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190507_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='need_online',
            field=models.BooleanField(default=False),
        ),
    ]
