# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_profile_need_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journals',
            old_name='journal_expiry_date',
            new_name='expiry_date',
        ),
        migrations.AlterField(
            model_name='journals',
            name='file',
            field=models.FileField(max_length=1000, upload_to='main/Journals/<django.db.models.fields.CharField>/'),
        ),
    ]
