# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190517_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='journals',
            name='file',
            field=models.FileField(max_length=1000, upload_to=main.models.upload_destination),
        ),
    ]
